const User = require('../models/user');
const Fridge = require('../models/fridge');
const Tag = require('../models/tag');
const jwt = require('jsonwebtoken');
const config = require("../config/dbconfig");
const issueJWT = require("../config/utils");
let allTags = [
    'Dinner',
   /* 'Starter',
    'Nut-Free',
    'Weeknight Meals',
    'Fry',
    'Shrimp',
    'Shellfish',
    'Seafood',
    'Coconut',
    'Fruit',
    'Lime',
    'Citrus',
    'Entertaining',
    'Weeknight',
    'Vegetarian',
    'Easy',
    'Quick',
    'Simmer',
    'Ravioli',
    'Pasta & Noodles',
    'Pasta',
    'Basil',
    'Pistachio',
    'Nut',
    'Walnut',
    'Salad',
    'Anchovy',
    'Fish',
    'Romaine',
    'Lettuce',
    'Leafy Greens',
    'Vegetable',
    'Parmesan',
    'Cheese',
    'Side',
    'Lunch',
    'Fruit Dessert',
    'Dessert',
    'American',
    'Strawberry',
    'Berry',
    'Summer',
    'Baking',
    'Fourth Of July',
    'Memorial Day',
    'Labor Day',
    'Gratin',
    'French',
    'European',
    'Potato',
    'Gruyère',
    'Russet Potato',
    'Fall',
    'Gluten-Free',
    'Thanksgiving',
    'Easter',
    'Salmon',
    'Bucatini',
    'Seaweed',
    'Cake',
    'Saffron',
    'Middle Eastern',
    'Ramadan',
    'Doughnut',
    'Yogurt',
    'Deep-fry',
    'Yeast',
    'Main',
    'Levantine',
    'Ground Beef',
    'Beef',
    'Meat',
    'Pappardelle',
    'Garlic',
    'Drinks',
    'Nonalcoholic',
    '5 Ingredients or Fewer',
    'Spring',
    'Mango',
    'Stone Fruit',
    'Breakfast',
    'Snack',
    'Muffin',
    'Pastries',
    'Carrot',
    'Stir-Fry',
    'Japanese',
    'East Asian',
    'Asian',
    'Udon Noodle',
    'Noodle',
    'Green Cabbage',
    'Cabbage',
    'Ground Pork',
    'Pork',
    'Dairy-Free',
    'Taco',
    'Mexican',
    'Latin American',
    'Pork Shoulder',
    'Grilling',
    'Cookie',
    'Cocoa',
    'Cocktail',
    'Mojito',
    'Mint',
    'Cuban',
    'Caribbean',
    'Italian',
    'Lemon',
    'Spaghetti',
    'Rum',
    'One-Pot Meals',
    'Sauté',
    'Trinidadian',
    'Rice',
    'Rice & Grains',
    'Pigeon Pea',
    'Bean',
    'Coconut Milk',
    'Vegan',
    'Vodka',
    'Canned Tomato',
    'Tomato',
    'Cashew',
    'Clam',
    'White Bean',
    'Cannellini Bean',
    'Toast',
    'Prosciutto',
    'Ham',
    'Serrano Ham',
    'Asparagus',
    'Persian',
    'Frittata',
    'Egg',
    'Zucchini',
    'Squash',
    'Summer Squash',
    'Leek',
    'Smoked Salmon',
    'Spinach',
    'Dill',
    'Cilantro',
    'Parsley',
    'Date',
    'Dried Fruit',
    'Radish',
    'Goat Cheese',
    'Chocolate',
    'Tahini',
    'Fingerling Potato',
    'Yukon Gold Potato',
    'Gouda',
    'Cheddar',
    'Layer Cake',
    'Raspberry',
    'Leg Of Lamb',
    'Lamb',
    'Braise',
    'Potato Salad',
    'Ramen',
    'Broccoli Rabe',
    'Rhubarb',
    'Ricotta',
    'Short Rib',
    'Sugar Snap Pea',
    'Pea',
    'Roast',
    'Gnocchi',
    'Sage',
    'Porcini Mushroom',
    'Mushroom',
    'Crème De Cassis',
    'Vermouth',
    'Salad Dressing',
    'Arugula',
    'Mâche',
    'Dip',
    'Crudité',
    'Tart',
    'Cherry',
    'Pea Shoot',
    'Tagliatelle',
    'Pecorino',
    'Pasta Shells',
    'Sausage',
    'Chicken',
    'Poultry',
    'Shallot',
    'Olive',
    'Orange',
    'Ground Chicken',
    'Ground Turkey',
    'Turkey',
    'Feta',
    'Za\'atar',
    'Kale',
    'Swiss Chard',
    'Castelvetrano Olive',
    'Sear',
    'Steak',
    'Scallion',
    'Onion',
    'Serrano Chile',
    'Chile',
    'Sandwich',
    'Sake',
    'Daikon',
    'Sauce',
    'Condiment',
    'Marinade',
    'Argentinean',
    'South American',
    'Oregano',
    'Soup',
    'Soups and Stews',
    'Jewish',
    'Matzo',
    'Raisin',
    'Cream Cheese',
    'Buttermilk',
    'Turkish',
    'Poach',
    'Aleppo-Style Pepper',
    'Chickpea',
    'Nutritional Yeast',
    'Cucumber',
    'Irish',
    'Brisket',
    'Stew',
    'Cajun & Creole',
    'Chicken Thigh',
    'Broccoli',
    'Keto',
    'Chinese',
    'Bok Choy',
    'Steam',
    'Lunar New Year',
    'Italian American',
    'Fettuccine',
    'Banana',
    'Pecan',
    'Greek',
    'Cauliflower',
    'Vietnamese',
    'Southeast Asian',
    'Rice Noodle',
    'Oyster Mushroom',
    'Tofu',
    'Shiitake Mushroom',
    'Kombu',
    'Red Lentil',
    'Lentil',
    'Super Bowl',
    'Fried Chicken',
    'Harissa',
    'Tex-Mex',
    'Jalapeño',
    'Ditalini',
    'Orzo',
    'Swordfish',
    'Mahi-Mahi',
    'Navy Bean',
    'Burger',
    'Bacon',
    'Cured Meat',
    'Kidney Bean',
    'Delicata Squash',
    'Fennel',
    'Apple',
    'Winter',
    'Pudding',
    'Grapefruit',
    'Guava',
    'Bar Cookie',
    'Passion Fruit',
    'Stock',
    'Taiwanese',
    'Portobello Mushroom',
    'Napa Cabbage',
    'Endive',
    'Chicory',
    'Sheet-Pan Dinners',
    'Sweet Potato',
    'Tomatillo',
    'Mozzarella',
    'Phyllo',
    'Southern',
    'Soul Food',
    'Rice and Grain Bowl',
    'Barley',
    'South Asian',
    'Halloumi',
    'Kielbasa',
    'Paprika',
    'Sun-Dried Tomato',
    'Pork Chop',
    'Sichuan Peppercorn',
    'Chile de Árbol',
    'Flaxseed Meal',
    'Oat',
    'Almond',
    'Grits',
    'Loaf Cake',
    'Turmeric',
    'Matcha',
    'Glutinous Rice Flour',
    'Indian',
    'Cardamom',
    'Bass',
    'Snapper',
    'Thai Chile',
    'Shanghainese',
    'Dumpling',
    'Kimchi',
    'Miso',
    'East African',
    'African',
    'Cod',
    'Crepe',
    'Pancake',
    'Filipino',
    'Haitian',
    'Bell Pepper',
    'Scotch Bonnet',
    'Habanero Chile',
    'Maitake Mushroom',
    'Casserole',
    'Spaghetti Squash',
    'Pisco',
    'Peruvian',
    'Mussel',
    'Duck',
    'Brazilian',
    'West African',
    'Okra',
    'Lamb Shoulder',
    'Peanut',
    'Black-Eyed Pea',
    'Eggplant',
    'Asian Pear',
    'Quinoa',
    'Pear',
    'Gorgonzola',
    'Blue Cheese',
    'Pineapple',
    'Chicken Breast',
    'Sherry',
    'Hazelnut',
    'Tarragon',
    'Radicchio',
    'Cotija',
    'Granola',
    'Tilapia',
    'St-Germain',
    'Tangerine',
    'Fresno Chile',
    'New Year\'s',
    'Christmas',
    'Cinnamon',
    'Central American',
    'Masa',
    'Pork Belly',
    'Pasilla Chile',
    'Ancho Chile',
    'Guajillo Chile',
    'Korean',
    'Korean Rice Cake',
    'Curry',
    'Kabocha Squash',
    'Crimini Mushroom',
    'Australian',
    'New Zealand',
    'Bread',
    'Collard Greens',
    'Mediterranean',
    'Brussels Sprout',
    'Iceberg Lettuce',
    'Mortadella',
    'Almond Flour',
    'Bake',
    'Cast iron',
    'Meatball',
    'Gluten Free',
    'Hot Drink',
    'Hot Chocolate',
    'Holiday Drinks',
    'Alcoholic',
    'Cognac/Armagnac',
    'Lasagna',
    'Pitcher Drink',
    'Blood Orange',
    'Holiday Cookies',
    'Colombia',
    'Punch',
    'Cranberry',
    'Hard Cider',
    'Coffee',
    'Avocado',
    'Quick And Easy',
    'Shortbread',
    'Prime Rib',
    'Frozen Dessert',
    'Ice Cream',
    'Maple',
    'Maple Syrup',
    'Peanut Butter',
    'Molasses',
    'Scone',
    'Egg Noodle',
    'Skewer',
    'Rib Eye',
    'Celery',
    'Savory Pie & Tart',
    'Puff Pastry',
    'Ginger',
    'Dark Chocolate',
    'White Chocolate',
    'Chipotle',
    'Green Bean',
    'Cherry Tomato',
    'Butternut Squash',
    'Rigatoni',
    'Horseradish',
    'Fritter',
    'appetizer',
    'Sichuan',
    'Red Onion',
    'herb',
    'Rice Pilaf',
    'Brown Butter',
    'Party',
    'French Fries',
    'honey',
    'Sriracha',
    'Vanilla',
    'Chorizo',
    'Stuffing',
    'Salami',
    'Biscuit',
    'Condiment/Spread',
    'Pie',
    'apple pie',
    'Rose Water',
    'Butter',
    'Jam',
    'Enchiladas',
    'Mole',
    'Frisée',
    'Cranberry Sauce',
    'Gravy',
    'Tea',
    'Bread Pudding',
    'Lychee',
    'Brioche',
    'Corn',
    'Hominy',
    'brussels sprout',
    'gochujang',
    'Lavender',
    'Ganache',
    'Loaf',
    'Mashed Potatoes',
    'Compote',
    'Puff Pastry Dough',
    'Pork Loin',
    'British',
    'Rolls',
    'Pumpkin',
    'Brunch',
    'Lemon Juice',
    'Olive Oil',
    'Caramel',
    'Meal Prep',
    'Soba Noodle',
    'Oatmeal',
    'Make Ahead',
    'Tostada',
    'Black Bean',
    'Queso Fresco',
    'Pizza',
    'French Lentil',
    'Black Lentil',
    'Porridge',
    'Escarole',
    'chard',
    'Fig',
    'Bulgur',
    'Burrito',
    'Wrap',
    'Winter Squash',
    'Breadcrumbs',
    'Waffle',
    'Lemongrass',
    'Grill',
    'Roasted Vegetables',
    'roast chicken',
    'Rye',
    'Lima Bean',
    'Pickle',
    'Crouton',
    'Flatbread',
    'Salvadoran',
    'Red Cabbage',
    'Raw',
    'Pickle and Preserve',
    'Poblano Chile',
    'Green Onion Scallion',
    'Oil',
    'gochugaru',
    'Sugar',
    'Chicken Broth',
    'Kosher Salt',
    'Fish Sauce',
    'Soy Sauce',
    'Black Pepper',
    'Greek Yogurt',
    'Lebanese',
    'Salsa',
    ' Udon',
    'Oyster Mushrooms',
    'Spanish',
    'Rice Flour',
    'Cold Soup',
    'Barbecue',
    'Tequila',
    'Hibiscus',
    'Haricot Vert',
    'Peach',
    'Chowder',
    'Curry Leaf',
    'Mackerel',
    'Tuna',
    'Sardine',
    'Trout',
    'Cold Drink',
    'Grape',
    'Ground Lamb',
    'Chicken Leg',
    'New Mexico Chile',
    'Heirloom Tomato',
    'Cantaloupe',
    'Melon',
    'Watermelon',
    'Aperol',
    'Nectarine',
    'Champagne',
    'Grand Marnier',
    'Mascarpone',
    'Nicaraguan',
    'Farro',
    'Wheat Berry',
    'Chinese Long Bean',
    'Paneer',
    'Parfait',
    'Veggie Burger',
    'Chicken Wing',
    'Shishito Pepper',
    'Chicken Drumstick',
    'Thai',
    'Anaheim Chile',
    'Laotian',
    'Blueberry',
    'Dried Apricot',
    'Blackberry',
    'Scallop',
    'Galette',
    'Graham Cracker',
    'Whole Wheat Flour',
    'Plum',
    'Grape Tomato',
    'Chive',
    'Green Lentil',
    'Manchego',
    'Thai Basil',
    'Cambodian',
    'Rib Eye Steak',
    'Galangal',
    'Thyme',
    'Marjoram',
    'Swedish',
    'Scandinavian',
    'Indonesian',
    'Tempeh',
    'Tamarind',
    'Palm Sugar',
    'Kwanzaa',
    'Juneteenth',
    'Risotto',
    'Pine Nut',
    'Sundae',
    'Jamaican',
    'Gin',
    'Monterey Jack',
    'Pinto Bean',
    'Broil',
    'Fava Bean',
    'Spreads',
    'Spring Onion',
    'Pakistani',
    'Arctic Char',
    'Rye Whiskey',
    'Whiskey',
    'Cognac',
    'Cornmeal',
    'Rosemary',
    'Mezcal',
    'Pomegranate',
    'Rosh Hashanah',
    'Native American',
    'Sumac',
    'Ramen Noodle',
    'Bison',
    'Green Tea',
    'Cheesecake',
    'Watercress',
    'Cake Flour',
    'Lamb Chop',
    'Savoy Cabbage',
    'Passover',
    'Hanukkah',
    'Slaw',
    'Beet',
    'Chili',
    'Penne',
    'Pilaf',
    'Artichoke',
    'Beef Tenderloin',
    'Ethiopian',
    'Cutlet',
    'Yuzu',
    'Moroccan',
    'North African',
    'Chutney',
    'Haddock',
    'Halibut',
    'Yemeni',
    'Chickpea Flour',
    'Oaxacan',
    'Martini',
    'Apple Cider',
    'Tortellini',
    'Hummus',
    'Hungarian',
    'Eastern European',
    'Red Skin Potato',
    'Iranian',
    'Beef Chuck',
    'Button Mushroom',
    'Turnip',
    'Fried Rice',
    'Orecchiette',
    'Brown Lentil',
    'Nachos',
    'Swiss Cheese',
    'Instant Pot',
    'Cantonese',
    'Armenian',
    'Hot Sauce',
    'Buckwheat',
    'Flaxseed',
    'Dried Currant',
    'Sorghum',
    'Macadamia Nut',
    'Mustard Greens',
    'Acorn Squash',
    'Freekeh',
    'Bourbon',
    'Amaro',
    'Absinthe',
    'Venezuelan',
    'Port',
    'Ceviche',
    'Crab',
    'Posole',
    'Cavatappi',
    'Macaroni',
    'Bread Flour',
    'Puerto Rican',
    'Glass Noodle',
    'Bangladeshi',
    'Ribs',
    'Chamomile Tea',
    'Candy',
    'Dough',
    'Plantain',
    'Pumpkin Seed',
    'Goat',
    'Plum Tomato',
    'Larb',
    'Branzino',
    'Nori',
    'Sorbet',
    'Rye Flour',
    'Palestinian',
    'Cobbler',
    'Campari',
    'Prune',
    'Sole',
    'Flounder',
    'Sprout',
    'Oxtail',
    'Meatloaf',
    'Guanciale',
    'New England',
    'Lobster',
    'Dried Cherry',
    'Wheat Germ',
    'Fusilli',
    'Dandelion Greens',
    'Ramps',
    'Brownie',
    'Dulce de Leche',
    'Earl Grey',
    'Mac and Cheese',
    'Pancetta',
    'Spelt',
    'Swiss',
    'Chia',
    'Pork Rib',
    'Dominican',
    'Scotch',
    'Polenta',
    'Provolone',
    'Pork Rib Roast',
    'Low Country Cuisine',
    'Sunflower Seed',
    'Panna Cotta',
    'Dal',
    'Malaysian',
    'Meyer Lemon',
    'Snack Bar',
    'Rib Roast',
    'Apricot',
    'Caviar',
    'Crumble',
    'Soppressata',
    'Gigante Bean',
    'Ricotta Salata',
    'Custard',
    'Romanesco',
    'Squid',
    'Escabèche',
    'Hearts of Palm',
    'Honeydew',
    'Jicama',
    'Lillet',
    'Cannabis',
    'Smoothie',
    'Pork Tenderloin',
    'Israeli couscous',
    'Couscous',
    'Fregola',
    'Black Cod',
    'Enoki Mushroom',
    'Quiche',
    'Clementine',
    'Persimmon',
    'coconut oil',
    'Vanilla Extract',
    'Parsnip',
    'Agua Fresca',
    'Linguine',
    'Cracker',
    'Smoked Trout',
    'Toffee',
    'Sicilian'*/
]
const functions = {
    signup: function (req, res) {
        if (!(req.body.email) || !(req.body.password) || !(req.body.fridgeName)) {
            if (!(req.body.email)) res.json({
                success: false,
                msg: "Enter email"
            });
            if (!(req.body.password)) res.json({
                success: false,
                msg: "Enter password"
            });
            if (!(req.body.fridgeName)) res.json({
                success: false,
                msg: "Enter fridge name"
            });
        } else {
            let newFridge = Fridge({
                fridgeName: req.body.fridgeName
            })
            let newUser = User({
                email: req.body.email,
                password: req.body.password,
                fridgeID: newFridge._id,
                passwordUpdateTime: Date.now()
            });
            newUser.save(function (err, newUser) {
                if (err) {
                    res.json({
                        success: false,
                        msg: "Failed to save"
                    });
                } else {
                    newFridge.save(function (err) {
                        if (err) return res.json({
                            success: false,
                            msg: "Failed to save fridge!"
                        })
                        res.json({
                            success: true,
                            msg: "Successfully saved"
                        })
                    });
                }
            })
        }
    },
    authenticate: function (req, res) {
        User.findOne({
            email: req.body.email
        }, function (err, user) {
            if (err) throw (err);
            if (!user) {
                res.status(403).send({
                    success: false,
                    msg: "Authentication failed. User not found"
                })
            } else {
                user.comparePassword(req.body.password, function (err, isMatch) {
                    if (isMatch && !err) {

                        const tokenObject = issueJWT(user);
                        res.status(200).json({success:true, token:tokenObject.token,expiresIn:tokenObject.expires})
                    } else {
                        res.status(403).send({
                            success: false,
                            msg: "Authentication failed. Wrong password"
                        });
                    }
                });
            }
        })
    },
    getinfo: function (req, res) {
        if(req.headers.authorization && req.headers.authorization.split(' ')[0] === "Bearer"){
            let token = req.headers.authorization.split(' ')[1];
            jwt.decode(token,config.secret);
            return res.json({success:true,msg:"Welcome!"})
        }else{
            return res.json({
                success: false,
                msg: "No Headers"
            });
        }

    },
    loadTags : function(req,res){
        for(let tag of allTags){
            let newTag = Tag({
                tagName:tag
            });
            console.log(newTag);
        }
    }
    
}
module.exports = functions